stages:
  - test

flutter_smoke_test:
  stage: test
  image: cirrusci/flutter:stable
  script:
    - flutter --version
    - flutter pub get
    - flutter analyze || true
    - flutter test || true